export {default as LandingPage} from './LandingPage'
export {default as HomePage} from './HomePage'
export {default as OverviewPage} from './OverviewPage'
export {default as TasksPage} from './TasksPage'
export {default as TodayTaskPage} from './TodayTaskPage'
export {default as StatusTasksPage} from './StatusTasksPage'
export {default as ManagerPage} from './ManagerPage'
export {default as HRPage} from './HRPage'